---
AWSTemplateFormatVersion: 2010-09-09
Description: CloudFront distribution with an S3 origin for Amazon ChimeSDK WS-102
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: s3-origin-chimesdk-workshops-fda-cloudboosta
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetObject
            Effect: Allow
            Principal:
              CanonicalUser: CfOriginAccessIdentity.S3CanonicalUserId
            Resource:
              - arn:aws:s3:::${S3Bucket}/*
  CfDistribution:
    Metadata:
      Comment: CloudFront distribution with an S3 origin for Amazon ChimeSDK WS-102
    Properties:
      DistributionConfig:
        Comment: CloudFront distribution with an S3 origin for Amazon ChimeSDK WS-102
        DefaultCacheBehavior:
          AllowedMethods:
            - HEAD
            - GET
          CachedMethods:
            - HEAD
            - GET
          Compress: false
          DefaultTTL: 86400
          ForwardedValues:
            Cookies:
              Forward: none
            Headers:
              - Origin
            QueryString: false
          MaxTTL: 31536000
          MinTTL: 86400
          TargetOriginId: s3-origin-${S3Bucket}
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http1.1
        IPV6Enabled: false
        Origins:
          - DomainName: !Ref S3Bucket.DomainName
            Id: s3-origin-${S3Bucket}
            OriginPath: ""
            S3OriginConfig:
              OriginAccessIdentity: origin-access-identity/cloudfront/${CfOriginAccessIdentity}
        PriceClass: PriceClass_All
    Type: AWS::CloudFront::Distribution
  CfOriginAccessIdentity:
    Metadata:
      Comment: Access S3 bucket content only through CloudFront
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: Access S3 bucket content only through CloudFront
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
Outputs:
  S3BucketName:
    Description: Bucket name
    Value: S3Bucket
  CfDistributionId:
    Description: Id for CloudFront distribution with an S3 origin for Amazon ChimeSDK WS-102
    Value: CfDistribution
  CfDistributionDomainName:
    Description: Domain name for CloudFront distribution with an S3 origin for
      Amazon ChimeSDK WS-102
    Value: CfDistribution.DomainName
